<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Comments on a wiki page (docs/features/wiki-comments.md).
 *
 * TWO tables, and the comment text is in NEITHER the document nor the page's HTML. The editor
 * stores only a `uid` inside a <mark>; everything a comment IS lives here. That separation is
 * what makes replies, resolve/reopen, permissions, history, deletion and real-time possible at
 * all — text baked into a document has no author, no timestamp, and no way to be replied to.
 *
 * A THREAD is one anchored conversation; a COMMENT is one message in it. Splitting them is what
 * lets a thread outlive its text: if the passage a thread points at is deleted, the thread is
 * marked `anchor_missing` and keeps every message, rather than disappearing with the sentence.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('wiki_page_comment_threads', function (Blueprint $table) {
            $table->id();
            $table->string('tenant_id');
            $table->foreignId('wiki_collection_id')->constrained('wiki_collections')->cascadeOnDelete();
            $table->foreignId('wiki_page_id')->constrained('wiki_pages')->cascadeOnDelete();

            // The id the DOCUMENT carries, inside <mark data-wk-threads="…">. Generated by the
            // client so the mark and the thread can be written in one round trip, and unique so
            // a duplicate can never make two threads answer to the same passage.
            $table->string('uid', 40)->unique();

            // The text the thread was attached to, as it read at the time. A COPY on purpose:
            // it is what the sidebar quotes, and it has to survive the passage being rewritten
            // or deleted — which is the case this whole feature has to get right.
            $table->text('quote')->nullable();

            $table->string('status', 20)->default('open');
            // Set when the <mark> is gone from the document: the thread stays, and says so.
            $table->boolean('anchor_missing')->default(false);

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('resolved_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('resolved_at')->nullable();
            $table->timestamps();

            $table->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete();
            // The sidebar's own query: this page's threads, open ones first, oldest first.
            $table->index(['wiki_page_id', 'status', 'id']);
        });

        Schema::create('wiki_page_comments', function (Blueprint $table) {
            $table->id();
            $table->string('tenant_id');
            $table->foreignId('thread_id')->constrained('wiki_page_comment_threads')->cascadeOnDelete();
            $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();
            $table->text('body');
            // Set on an edit, so "edited" can be shown honestly rather than inferred from
            // updated_at — which also moves for reasons that are not edits.
            $table->timestamp('edited_at')->nullable();
            $table->timestamps();
            // Soft, not hard: a deleted message must not renumber or orphan the replies that
            // answered it, and "who said what" is the one thing a thread cannot reconstruct.
            $table->softDeletes();

            $table->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete();
            $table->index(['thread_id', 'id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('wiki_page_comments');
        Schema::dropIfExists('wiki_page_comment_threads');
    }
};
